#pragma once
#include "types/enum.hpp"

namespace oic {

	//Mapping to a USHORT VK keycode

	oicExposedEnum(

		WKey, u16,

		KEY_0 = 0x30, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9,
		KEY_A = 0x41, KEY_B, KEY_C, KEY_D, KEY_E, KEY_F, KEY_G, KEY_H, KEY_I, KEY_J,
		KEY_K, KEY_L, KEY_M, KEY_N, KEY_O, KEY_P, KEY_Q, KEY_R, KEY_S, KEY_T,
		KEY_U, KEY_V, KEY_W, KEY_X, KEY_Y, KEY_Z,

		KEY_BACKSPACE = 0x08, KEY_SPACE = 0x20, KEY_TAB = 0x09, KEY_SHIFT = 0x10, KEY_CTRL = 0x11, KEY_ALT = 0x12,
		KEY_PAUSE = 0x13, KEY_CAPS_LOCK = 0x14, KEY_ESCAPE = 0x1B, KEY_PAGE_UP = 0x21, KEY_PAGE_DOWN = 0x22,
		KEY_END = 0x23, KEY_HOME = 0x24, KEY_SELECT = 0x29, KEY_PRINT = 0x2A, KEY_EXECUTE = 0x2B, KEY_PRINT_SCREEN = 0x2C,
		KEY_INSERT = 0x2D, KEY_DELETE = 0x2E, KEY_HELP = 0x2F, KEY_MENU = 0x5B, KEY_NUM_LOCK = 0x90, KEY_SCROLL_LOCK = 0x91,
		KEY_APPS = 0x5D, KEY_BACK = 0xA6, KEY_FORWARD = 0xA7, KEY_SLEEP = 0x5F, KEY_REFRESH = 0xA8, KEY_STOP = 0xA9, KEY_SEARCH = 0xAA,
		KEY_FAVORITES = 0xAB, KEY_START = 0xAC, KEY_MUTE = 0xAD, KEY_VOLUME_DOWN = 0xAE, KEY_VOLUME_UP = 0xAF,
		KEY_SKIP = 0xB0, KEY_PREVIOUS = 0xB1, KEY_CLEAR = 0xFE, KEY_ZOOM = 0xFB,

		KEY_LEFT = 0x25, KEY_RIGHT = 0x26, KEY_UP = 0x27, KEY_DOWN = 0x28, 

		KEY_NUMPAD_1 = 0x61, KEY_NUMPAD_2, KEY_NUMPAD_3,
		KEY_NUMPAD_4, KEY_NUMPAD_5, KEY_NUMPAD_6,
		KEY_NUMPAD_7, KEY_NUMPAD_8, KEY_NUMPAD_9,
		KEY_NUMPAD_0 = 0x60, KEY_NUMPAD_MULTIPLY = 0x6A, KEY_NUMPAD_ADD = 0x6B,
		KEY_NUMPAD_DECIMAL = 0x6E, KEY_NUMPAD_DIVIDE = 0x6F, KEY_NUMPAD_SUBTRACT = 0x6D,

		KEY_F1 = 0x70, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9,
		KEY_F12, KEY_F13, KEY_F14, KEY_F15, KEY_F16, KEY_F17, KEY_F18, KEY_F19,
		KEY_F20, KEY_F21, KEY_F22, KEY_F23, KEY_F24,

		KEY_PLUS = 0xBB, KEY_COMMA = 0xBC, KEY_MINUS = 0xBD, KEY_PERIOD = 0xBE, 

		KEY_SLASH = 0xBF, KEY_TILDE = 0xC0, KEY_SEMICOLON = 0xBA, KEY_BEGIN_BRACKET = 0xDB, KEY_END_BRACKET = 0xDD, KEY_PIPE = 0xDC,
		KEY_QUOTE = 0xDE
	);

}